# Generated by Django 6.0 on 2025-12-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_month_student_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='month',
            new_name='join_month',
        ),
    ]
