# Generated by Django 6.0 on 2025-12-11 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_month_student_join_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
